//
//  TwelvethViewController.swift
//  CleaningApp
//
//  Created by Bogdan Barbulescu on 08/08/2016.
//  Copyright © 2016 brev. All rights reserved.
//

import UIKit
import FirebaseDatabase
import FirebaseAuth


class TwelvethViewController: UIViewController {

    var dbRef: FIRDatabaseReference!
    var userLoggedIn:String!

    
    override func viewDidLoad() {
        super.viewDidLoad()
      
        
        // create a child in our Database with the name "Users"
dbRef = FIRDatabase.database().reference().child("Users")
        
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(true)
        
        // check if user is singed in
        if FIRAuth.auth() != nil {
            let userSignedIn = FIRAuth.auth()?.currentUser?.uid
                
                // pass the userID to userLoggedIn variable
                self.userLoggedIn = userSignedIn
                    StructS.myUid = userSignedIn //  StructS is in FullData.swift
                
            }
        }


    // generate a random number to be used as Booking ref# later on
    func randomInt(min: Int, max:Int) -> Int {
        return min + Int(arc4random_uniform(UInt32(max - min + 1)))
    }


    @IBAction func saveToDB(sender: AnyObject) {
        let bookingNumberGenerated = random9DigitString()
            
            // 100000000 + Int(arc4random_uniform(1000000000))
        
        
        // assign the booking number to  FullData.finalBookingNumber
        FullData.finalBookingNumber = bookingNumberGenerated
      
        
          // get data from FullData structure
           let BookingAmount = FullData.finalBookingAmount
           let BookingNumber = FullData.finalBookingNumber
           let PostCode = FullData.finalPostCode
           let SelectedBathRow = FullData.finalSelectedBathRow
           let SelectedBedRow = FullData.finalSelectedBedRow
           let DateAndTime = FullData.finalDateAndTime
           let FrequencyName = FullData.finalFrequencyName
           let FrequecyAmount = FullData.finalFrequecyAmount
        
        //get the boolean value from extrasSelected structure for each row that was selected
        let insideCabinets = extrasSelected[0].selected
        let insideFridge = extrasSelected[1].selected
        let insideOven = extrasSelected[2].selected
        let laundryWash = extrasSelected[3].selected
        let interiorWindows = extrasSelected[4].selected
        
           let FullName = FullData.finalfullName
           let SuppliesName = FullData.finalSuppliesName
           let SuppliesAmount =  FullData.finalSuppliesAmount
           let FlatNumber = FullData.finalflatNumber
           let StreetAddress = FullData.finalstreetAddress
           let PhoneNumber = FullData.finalphoneNumber
           let EmailAddress = FullData.finalemailAddress
        
  // create an instance of FireBaseData and pass the data from FullData structure as arguments
        let instanceFireBaseData = FireBaseData(
            BookingAmount:BookingAmount,
            BookingNumber:BookingNumber,
            PostCode: PostCode,
            SelectedBathRow: SelectedBathRow,
            SelectedBedRow: SelectedBedRow,
            DateAndTime: DateAndTime,
            FrequencyName: FrequencyName,
            FrequecyAmount: FrequecyAmount,
            insideCabinets: insideCabinets,
            insideFridge: insideFridge,
            insideOven: insideOven,
            laundryWash: laundryWash,
            interiorWindows: interiorWindows,
            FullName: FullName,
            SuppliesName: SuppliesName,
            SuppliesAmount: SuppliesAmount,
            FlatNumber: FlatNumber,
            StreetAddress: StreetAddress,
            PhoneNumber: PhoneNumber,
            EmailAddress:EmailAddress)
        

        // create a child in Firebase with the .uid value of the userLoggedIn
         // create another child with a value generated by randomgenearator to be used as Booking Number when retrieving the data.
           let contentRef = self.dbRef.child(userLoggedIn).child(bookingNumberGenerated)
      
       // convert the values of instanceFireBaseData to AnyObject type and assign them to contentRef Firebase path
                contentRef.setValue(instanceFireBaseData.toAnyObject())
    }
    
    // generate a random number
    func random9DigitString() -> String {
        let min: UInt32 = 100_000_000
        let max: UInt32 = 999_999_999
        let i = min + arc4random_uniform(max - min + 1)
        return String(i)
    }
}



